import { Typography, makeStyles } from '@material-ui/core'
import { CallMissedSharp } from '@material-ui/icons'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Homepage/Header'
import MainSection from '../components/Homepage/Main Section/MainSection'

const useStyles = makeStyles((theme) => ({
  body: {
      margin: '0px 100px',
      [theme.breakpoints.down(960)]: {
        margin: "0px 10px"                   // secondary
      }
  },
}),
{index:1})


export default function Home() {
  
  const classes = useStyles(); 

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <br></br>
      <div className={classes.body}>
        <MainSection  />        
      </div>
      </div>  
  )
}
